config/routes.rb
Rails.application.routes.draw do

  root 'ideas#index'

    put '/ideas/:id/quality', to: 'ideas#change_quality'

    resources :ideas, only: [:create, :edit, :update, :destroy]

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  enum quality: [ :swill, :plausible, :genius ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  respond_to :html, :json, :xml
  before_action :get_idea, only: [:edit, :update, :change_quality, :destroy]

  def index
    @idea  = Idea.new
    @ideas = Idea.order(created_at: :desc)
  end

  def create
    idea = Idea.create(idea_params)
    render partial: "idea", locals: {idea: idea}
  end

  def edit
  end

  def update
    @idea.update_attributes(idea_params)
    redirect_to root_path
  end

  def change_quality
    @idea.update_attributes(quality: params[:quality].to_i)
    head :ok
  end

  def destroy
    @idea.destroy
    head :ok
  end

  private

  def get_idea
    @idea = Idea.find(params[:id])
  end

  def idea_params
    params.require(:idea).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/idea_helper.rb
module IdeaHelper
  def format_body(idea)
    truncate(idea.body, length: 100, separator: " ")
  end
end

app/views/ideas/_idea.html.erb
 <li class="idea" id="<%= idea.id %>">
    <h1 class="title"><%= idea.title %></h1>
    <h3 class="body"><%= format_body(idea) %></h3>
    <%= link_to "Edit", edit_idea_path(idea), class: "btn btn-md btn-primary" %>
    <button class="delete btn btn-md btn-primary">Delete</button>
    <br>
    <br>
    <h4 class="quality"><%= idea.quality.capitalize %></h4>
    <button class="thumbsup btn btn-sm btn-success">Thumbs Up</button> <button class="thumbsdown btn btn-sm btn-danger">Thumbs Down</button>
    <hr>
  </li>

app/views/ideas/edit.html.erb
<%= form_for @idea, html: {id: "edit-idea-form" } do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, value: @idea.title, id: "title-field" %>

  <%= f.label :body %>
  <%= f.text_field :body, value: @idea.body, id: "body-field" %>

  <%= f.submit class: "btn btn-md btn-primary"%>
<% end %>

app/views/ideas/index.html.erb
<div class="container">
<%= form_for @idea, html: {id: "new-idea-form" } do |f| %>
<div class="form-group new-form">
  <%= f.text_field :title, id: "title-field", placeholder: "Idea Title" %>
  <%= f.text_field :body, id: "body-field", placeholder: "Idea Content" %>
  <%= f.submit class: "btn btn-md btn-primary" %>
<% end %>
</div>

<form>
  <div class="form-group">
  <input type="text" id="idea-search" placeholder="Search Ideas">
</div>
</form>

<ul id="ideas" class="list-group">
  <% @ideas.each do |idea| %>
    <%= render partial: "idea", locals: {idea: idea} %>
  <% end %>
</ul>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">IdeaBox 2.0</a>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ideabox2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: 'layouts/navbar' %>
<%= yield %>

</body>
</html>